# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-085f2dd0-75bc-471b-a51d-8ddc0678b3f9";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-085f2dd0-75bc-471b-a51d-8ddc0678b3f9".device = "/dev/disk/by-uuid/085f2dd0-75bc-471b-a51d-8ddc0678b3f9";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-085f2dd0-75bc-471b-a51d-8ddc0678b3f9";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-085f2dd0-75bc-471b-a51d-8ddc0678b3f9";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6A82-BD5A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-cce3f8be-1366-44f4-82ea-242cec24b6b6"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
